/**
 * Embedded AI Component Fixtures for Test-Driven Development
 * 
 * This file contains real AI-generated components embedded as strings to eliminate
 * file system dependencies in Cloudflare Workers runtime tests. These fixtures
 * enable proper E2E testing by providing reliable test data that doesn't depend
 * on Node.js fs APIs.
 */

// React TodoList Component - Generated by ChatGPT/Claude
export const reactTodoComponent = `import React, { useState } from 'react';

const TodoList = () => {
  const [todos, setTodos] = useState([]);
  const [inputValue, setInputValue] = useState('');

  const addTodo = () => {
    if (inputValue.trim() !== '') {
      setTodos([...todos, { id: Date.now(), text: inputValue, completed: false }]);
      setInputValue('');
    }
  };

  const toggleTodo = (id) => {
    setTodos(todos.map(todo =>
      todo.id === id ? { ...todo, completed: !todo.completed } : todo
    ));
  };

  const deleteTodo = (id) => {
    setTodos(todos.filter(todo => todo.id !== id));
  };

  return (
    <div style={{ padding: '20px', maxWidth: '500px', margin: '0 auto' }}>
      <h1>Todo List</h1>
      <div style={{ marginBottom: '20px' }}>
        <input
          type="text"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          onKeyPress={(e) => e.key === 'Enter' && addTodo()}
          placeholder="Add a new todo..."
          style={{ padding: '10px', width: '70%', marginRight: '10px' }}
        />
        <button onClick={addTodo} style={{ padding: '10px' }}>
          Add Todo
        </button>
      </div>
      <ul style={{ listStyle: 'none', padding: 0 }}>
        {todos.map(todo => (
          <li key={todo.id} style={{ marginBottom: '10px', display: 'flex', alignItems: 'center' }}>
            <input
              type="checkbox"
              checked={todo.completed}
              onChange={() => toggleTodo(todo.id)}
              style={{ marginRight: '10px' }}
            />
            <span style={{ 
              flex: 1, 
              textDecoration: todo.completed ? 'line-through' : 'none',
              color: todo.completed ? '#888' : '#000'
            }}>
              {todo.text}
            </span>
            <button onClick={() => deleteTodo(todo.id)} style={{ marginLeft: '10px' }}>
              Delete
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default TodoList;`;

// React TypeScript Counter Component - Generated by AI
export const reactTypescriptComponent = `import React, { useState } from 'react';

interface CounterProps {
  initialValue?: number;
  step?: number;
}

const Counter: React.FC<CounterProps> = ({ initialValue = 0, step = 1 }) => {
  const [count, setCount] = useState<number>(initialValue);

  const increment = (): void => {
    setCount(prevCount => prevCount + step);
  };

  const decrement = (): void => {
    setCount(prevCount => prevCount - step);
  };

  const reset = (): void => {
    setCount(initialValue);
  };

  return (
    <div style={{ 
      display: 'flex', 
      flexDirection: 'column', 
      alignItems: 'center', 
      padding: '20px',
      fontFamily: 'Arial, sans-serif'
    }}>
      <h1>Counter App</h1>
      <div style={{ 
        fontSize: '48px', 
        fontWeight: 'bold', 
        margin: '20px 0',
        color: count > 0 ? 'green' : count < 0 ? 'red' : 'black'
      }}>
        {count}
      </div>
      <div style={{ display: 'flex', gap: '10px' }}>
        <button 
          onClick={decrement}
          style={{ 
            padding: '10px 20px', 
            fontSize: '16px',
            backgroundColor: '#ff6b6b',
            color: 'white',
            border: 'none',
            borderRadius: '5px',
            cursor: 'pointer'
          }}
        >
          - {step}
        </button>
        <button 
          onClick={reset}
          style={{ 
            padding: '10px 20px', 
            fontSize: '16px',
            backgroundColor: '#95a5a6',
            color: 'white',
            border: 'none',
            borderRadius: '5px',
            cursor: 'pointer'
          }}
        >
          Reset
        </button>
        <button 
          onClick={increment}
          style={{ 
            padding: '10px 20px', 
            fontSize: '16px',
            backgroundColor: '#51cf66',
            color: 'white',
            border: 'none',
            borderRadius: '5px',
            cursor: 'pointer'
          }}
        >
          + {step}
        </button>
      </div>
    </div>
  );
};

export default Counter;`;

// Vue 3 Composition API Component - Generated by AI
export const vueCompositionComponent = `<template>
  <div class="weather-app">
    <h1>Weather Dashboard</h1>
    <div class="search-section">
      <input 
        v-model="city" 
        @keyup.enter="fetchWeather"
        placeholder="Enter city name..."
        class="city-input"
      />
      <button @click="fetchWeather" :disabled="loading" class="search-btn">
        {{ loading ? 'Loading...' : 'Get Weather' }}
      </button>
    </div>
    
    <div v-if="weather" class="weather-card">
      <h2>{{ weather.city }}</h2>
      <div class="temperature">{{ weather.temperature }}°C</div>
      <div class="description">{{ weather.description }}</div>
      <div class="details">
        <span>Humidity: {{ weather.humidity }}%</span>
        <span>Wind: {{ weather.windSpeed }} km/h</span>
      </div>
    </div>
    
    <div v-if="error" class="error">
      {{ error }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue';

interface Weather {
  city: string;
  temperature: number;
  description: string;
  humidity: number;
  windSpeed: number;
}

const city = ref<string>('');
const loading = ref<boolean>(false);
const error = ref<string>('');
const weather = ref<Weather | null>(null);

const fetchWeather = async (): Promise<void> => {
  if (!city.value.trim()) {
    error.value = 'Please enter a city name';
    return;
  }
  
  loading.value = true;
  error.value = '';
  weather.value = null;
  
  try {
    // Simulate API call with mock data
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    weather.value = {
      city: city.value,
      temperature: Math.floor(Math.random() * 35) + 5,
      description: ['Sunny', 'Cloudy', 'Rainy', 'Snowy'][Math.floor(Math.random() * 4)],
      humidity: Math.floor(Math.random() * 100),
      windSpeed: Math.floor(Math.random() * 30) + 5
    };
  } catch (err) {
    error.value = 'Failed to fetch weather data';
  } finally {
    loading.value = false;
  }
};
</script>

<style scoped>
.weather-app {
  max-width: 400px;
  margin: 0 auto;
  padding: 20px;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

.search-section {
  display: flex;
  gap: 10px;
  margin-bottom: 20px;
}

.city-input {
  flex: 1;
  padding: 12px;
  border: 2px solid #e1e8ed;
  border-radius: 8px;
  font-size: 16px;
}

.search-btn {
  padding: 12px 20px;
  background: #1da1f2;
  color: white;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  font-size: 16px;
}

.search-btn:disabled {
  background: #aaa;
  cursor: not-allowed;
}

.weather-card {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 30px;
  border-radius: 15px;
  text-align: center;
}

.temperature {
  font-size: 48px;
  font-weight: bold;
  margin: 15px 0;
}

.description {
  font-size: 20px;
  margin-bottom: 20px;
}

.details {
  display: flex;
  justify-content: space-around;
  font-size: 14px;
}

.error {
  background: #ff6b6b;
  color: white;
  padding: 15px;
  border-radius: 8px;
  text-align: center;
}
</style>`;

// Svelte Component - Generated by AI
export const svelteComponent = `<script lang="ts">
  interface Task {
    id: number;
    text: string;
    completed: boolean;
    priority: 'low' | 'medium' | 'high';
  }

  let tasks: Task[] = [];
  let newTaskText = '';
  let selectedPriority: 'low' | 'medium' | 'high' = 'medium';
  let filter: 'all' | 'active' | 'completed' = 'all';

  function addTask(): void {
    if (newTaskText.trim()) {
      const newTask: Task = {
        id: Date.now(),
        text: newTaskText.trim(),
        completed: false,
        priority: selectedPriority
      };
      tasks = [...tasks, newTask];
      newTaskText = '';
    }
  }

  function toggleTask(id: number): void {
    tasks = tasks.map(task => 
      task.id === id ? { ...task, completed: !task.completed } : task
    );
  }

  function deleteTask(id: number): void {
    tasks = tasks.filter(task => task.id !== id);
  }

  function clearCompleted(): void {
    tasks = tasks.filter(task => !task.completed);
  }

  $: filteredTasks = tasks.filter(task => {
    if (filter === 'active') return !task.completed;
    if (filter === 'completed') return task.completed;
    return true;
  });

  $: taskStats = {
    total: tasks.length,
    active: tasks.filter(t => !t.completed).length,
    completed: tasks.filter(t => t.completed).length
  };

  function getPriorityColor(priority: string): string {
    switch (priority) {
      case 'high': return '#ff4757';
      case 'medium': return '#ffa502';
      case 'low': return '#7bed9f';
      default: return '#70a1ff';
    }
  }
</script>

<main>
  <h1>Advanced Todo App</h1>
  
  <div class="add-task">
    <input
      bind:value={newTaskText}
      on:keydown={(e) => e.key === 'Enter' && addTask()}
      placeholder="What needs to be done?"
      class="task-input"
    />
    <select bind:value={selectedPriority} class="priority-select">
      <option value="low">Low Priority</option>
      <option value="medium">Medium Priority</option>
      <option value="high">High Priority</option>
    </select>
    <button on:click={addTask} class="add-btn">Add Task</button>
  </div>

  <div class="stats">
    <span>Total: {taskStats.total}</span>
    <span>Active: {taskStats.active}</span>
    <span>Completed: {taskStats.completed}</span>
  </div>

  <div class="filters">
    <button 
      class="filter-btn" 
      class:active={filter === 'all'}
      on:click={() => filter = 'all'}
    >
      All
    </button>
    <button 
      class="filter-btn" 
      class:active={filter === 'active'}
      on:click={() => filter = 'active'}
    >
      Active
    </button>
    <button 
      class="filter-btn" 
      class:active={filter === 'completed'}
      on:click={() => filter = 'completed'}
    >
      Completed
    </button>
  </div>

  <ul class="task-list">
    {#each filteredTasks as task (task.id)}
      <li class="task-item" class:completed={task.completed}>
        <input
          type="checkbox"
          checked={task.completed}
          on:change={() => toggleTask(task.id)}
          class="task-checkbox"
        />
        <span 
          class="task-text"
          style="border-left: 4px solid {getPriorityColor(task.priority)}"
        >
          {task.text}
        </span>
        <span class="priority-badge" style="background: {getPriorityColor(task.priority)}">
          {task.priority}
        </span>
        <button on:click={() => deleteTask(task.id)} class="delete-btn">
          ×
        </button>
      </li>
    {/each}
  </ul>

  {#if tasks.filter(t => t.completed).length > 0}
    <button on:click={clearCompleted} class="clear-btn">
      Clear Completed
    </button>
  {/if}
</main>

<style>
  main {
    max-width: 600px;
    margin: 0 auto;
    padding: 20px;
    font-family: 'Inter', sans-serif;
  }

  h1 {
    text-align: center;
    color: #2c3e50;
    margin-bottom: 30px;
  }

  .add-task {
    display: flex;
    gap: 10px;
    margin-bottom: 20px;
  }

  .task-input {
    flex: 1;
    padding: 12px;
    border: 2px solid #e1e8ed;
    border-radius: 8px;
    font-size: 16px;
  }

  .priority-select {
    padding: 12px;
    border: 2px solid #e1e8ed;
    border-radius: 8px;
    font-size: 16px;
  }

  .add-btn {
    padding: 12px 20px;
    background: #3498db;
    color: white;
    border: none;
    border-radius: 8px;
    cursor: pointer;
    font-size: 16px;
  }

  .stats {
    display: flex;
    justify-content: space-between;
    margin-bottom: 20px;
    padding: 15px;
    background: #f8f9fa;
    border-radius: 8px;
  }

  .filters {
    display: flex;
    gap: 10px;
    margin-bottom: 20px;
  }

  .filter-btn {
    padding: 8px 16px;
    border: 2px solid #e1e8ed;
    background: white;
    border-radius: 6px;
    cursor: pointer;
  }

  .filter-btn.active {
    background: #3498db;
    color: white;
    border-color: #3498db;
  }

  .task-list {
    list-style: none;
    padding: 0;
  }

  .task-item {
    display: flex;
    align-items: center;
    gap: 15px;
    padding: 15px;
    border: 1px solid #e1e8ed;
    border-radius: 8px;
    margin-bottom: 10px;
    transition: all 0.2s ease;
  }

  .task-item:hover {
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  }

  .task-item.completed {
    opacity: 0.6;
    background: #f8f9fa;
  }

  .task-checkbox {
    width: 20px;
    height: 20px;
  }

  .task-text {
    flex: 1;
    padding-left: 15px;
    font-size: 16px;
  }

  .task-item.completed .task-text {
    text-decoration: line-through;
  }

  .priority-badge {
    padding: 4px 8px;
    border-radius: 12px;
    color: white;
    font-size: 12px;
    font-weight: bold;
    text-transform: uppercase;
  }

  .delete-btn {
    width: 30px;
    height: 30px;
    border: none;
    background: #e74c3c;
    color: white;
    border-radius: 50%;
    cursor: pointer;
    font-size: 18px;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .clear-btn {
    width: 100%;
    padding: 12px;
    background: #e74c3c;
    color: white;
    border: none;
    border-radius: 8px;
    cursor: pointer;
    font-size: 16px;
    margin-top: 20px;
  }
</style>`;

// HTML + Vanilla JavaScript Component - Generated by AI  
export const htmlVanillaComponent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interactive Calculator</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        }

        .calculator {
            background: white;
            border-radius: 20px;
            padding: 20px;
            box-shadow: 0 20px 40px rgba(0,0,0,0.1);
            width: 300px;
        }

        .display {
            background: #f8f9fa;
            border: none;
            border-radius: 10px;
            padding: 20px;
            font-size: 24px;
            text-align: right;
            margin-bottom: 20px;
            width: 100%;
            box-sizing: border-box;
        }

        .buttons {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 10px;
        }

        button {
            padding: 20px;
            font-size: 18px;
            border: none;
            border-radius: 10px;
            cursor: pointer;
            transition: all 0.2s ease;
        }

        .number, .decimal {
            background: #e9ecef;
            color: #495057;
        }

        .operator {
            background: #007bff;
            color: white;
        }

        .equals {
            background: #28a745;
            color: white;
        }

        .clear {
            background: #dc3545;
            color: white;
        }

        button:hover {
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(0,0,0,0.2);
        }

        button:active {
            transform: translateY(0);
        }

        .zero {
            grid-column: span 2;
        }
    </style>
</head>
<body>
    <div class="calculator">
        <input type="text" class="display" id="display" readonly value="0">
        <div class="buttons">
            <button class="clear" onclick="clearDisplay()">C</button>
            <button class="clear" onclick="deleteLast()">⌫</button>
            <button class="operator" onclick="appendToDisplay('/')">/</button>
            <button class="operator" onclick="appendToDisplay('*')">×</button>
            
            <button class="number" onclick="appendToDisplay('7')">7</button>
            <button class="number" onclick="appendToDisplay('8')">8</button>
            <button class="number" onclick="appendToDisplay('9')">9</button>
            <button class="operator" onclick="appendToDisplay('-')">-</button>
            
            <button class="number" onclick="appendToDisplay('4')">4</button>
            <button class="number" onclick="appendToDisplay('5')">5</button>
            <button class="number" onclick="appendToDisplay('6')">6</button>
            <button class="operator" onclick="appendToDisplay('+')">+</button>
            
            <button class="number" onclick="appendToDisplay('1')">1</button>
            <button class="number" onclick="appendToDisplay('2')">2</button>
            <button class="number" onclick="appendToDisplay('3')">3</button>
            <button class="equals" onclick="calculate()" rowspan="2">=</button>
            
            <button class="number zero" onclick="appendToDisplay('0')">0</button>
            <button class="decimal" onclick="appendToDisplay('.')">.</button>
        </div>
    </div>

    <script>
        let display = document.getElementById('display');
        let currentInput = '0';
        let shouldResetDisplay = false;

        function appendToDisplay(value) {
            if (shouldResetDisplay) {
                currentInput = '';
                shouldResetDisplay = false;
            }
            
            if (currentInput === '0' && value !== '.') {
                currentInput = value;
            } else {
                currentInput += value;
            }
            
            updateDisplay();
        }

        function updateDisplay() {
            display.value = currentInput;
        }

        function clearDisplay() {
            currentInput = '0';
            updateDisplay();
        }

        function deleteLast() {
            if (currentInput.length > 1) {
                currentInput = currentInput.slice(0, -1);
            } else {
                currentInput = '0';
            }
            updateDisplay();
        }

        function calculate() {
            try {
                // Replace display symbols with JavaScript operators
                let expression = currentInput.replace(/×/g, '*');
                let result = eval(expression);
                
                // Handle division by zero and other errors
                if (!isFinite(result)) {
                    currentInput = 'Error';
                } else {
                    currentInput = result.toString();
                }
                
                shouldResetDisplay = true;
                updateDisplay();
            } catch (error) {
                currentInput = 'Error';
                shouldResetDisplay = true;
                updateDisplay();
            }
        }

        // Keyboard support
        document.addEventListener('keydown', function(event) {
            const key = event.key;
            
            if (key >= '0' && key <= '9') {
                appendToDisplay(key);
            } else if (key === '.') {
                appendToDisplay('.');
            } else if (key === '+' || key === '-') {
                appendToDisplay(key);
            } else if (key === '*') {
                appendToDisplay('*');
            } else if (key === '/') {
                event.preventDefault(); // Prevent browser search
                appendToDisplay('/');
            } else if (key === 'Enter' || key === '=') {
                calculate();
            } else if (key === 'Escape' || key === 'Delete') {
                clearDisplay();
            } else if (key === 'Backspace') {
                deleteLast();
            }
        });
    </script>
</body>
</html>`;

// Complex React Component with Backend Integration - Generated by AI
export const complexReactComponent = `import React, { useState, useEffect, useCallback } from 'react';

interface User {
  id: number;
  name: string;
  email: string;
  avatar?: string;
  status: 'online' | 'offline' | 'away';
}

interface Message {
  id: number;
  userId: number;
  text: string;
  timestamp: Date;
  edited?: boolean;
}

const ChatApp: React.FC = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [messages, setMessages] = useState<Message[]>([]);
  const [currentMessage, setCurrentMessage] = useState<string>('');
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string>('');

  // Simulate API calls with mock data
  const mockUsers: User[] = [
    { id: 1, name: 'Alice Johnson', email: 'alice@example.com', status: 'online' },
    { id: 2, name: 'Bob Smith', email: 'bob@example.com', status: 'away' },
    { id: 3, name: 'Carol Williams', email: 'carol@example.com', status: 'offline' },
  ];

  const mockMessages: Message[] = [
    { id: 1, userId: 1, text: 'Hey everyone! How is everyone doing today?', timestamp: new Date(Date.now() - 3600000) },
    { id: 2, userId: 2, text: 'Hi Alice! I\\'m doing great, just working on some new features.', timestamp: new Date(Date.now() - 3000000) },
    { id: 3, userId: 3, text: 'Hello! I\\'m good too. Just finished a big project.', timestamp: new Date(Date.now() - 1800000) },
  ];

  // Initialize app
  useEffect(() => {
    const initializeApp = async () => {
      try {
        setIsLoading(true);
        // Simulate API delay
        await new Promise(resolve => setTimeout(resolve, 1000));
        
        setUsers(mockUsers);
        setMessages(mockMessages);
        setCurrentUser(mockUsers[0]); // Set first user as current
        setError('');
      } catch (err) {
        setError('Failed to load chat data');
      } finally {
        setIsLoading(false);
      }
    };

    initializeApp();
  }, []);

  const sendMessage = useCallback(async () => {
    if (!currentMessage.trim() || !currentUser) return;

    const newMessage: Message = {
      id: Date.now(),
      userId: currentUser.id,
      text: currentMessage.trim(),
      timestamp: new Date(),
    };

    try {
      // Simulate sending message to backend
      await new Promise(resolve => setTimeout(resolve, 200));
      
      setMessages(prev => [...prev, newMessage]);
      setCurrentMessage('');
    } catch (err) {
      setError('Failed to send message');
    }
  }, [currentMessage, currentUser]);

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  const formatTimestamp = (date: Date): string => {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  const getUserById = (userId: number): User | undefined => {
    return users.find(user => user.id === userId);
  };

  const getStatusColor = (status: User['status']): string => {
    switch (status) {
      case 'online': return '#10b981';
      case 'away': return '#f59e0b';
      case 'offline': return '#6b7280';
      default: return '#6b7280';
    }
  };

  if (isLoading) {
    return (
      <div style={{ 
        display: 'flex', 
        justifyContent: 'center', 
        alignItems: 'center', 
        height: '100vh',
        flexDirection: 'column'
      }}>
        <div style={{ fontSize: '18px', marginBottom: '10px' }}>Loading chat...</div>
        <div style={{ 
          width: '40px', 
          height: '40px', 
          border: '4px solid #f3f3f3',
          borderTop: '4px solid #3498db',
          borderRadius: '50%',
          animation: 'spin 1s linear infinite'
        }}></div>
      </div>
    );
  }

  return (
    <div style={{ 
      display: 'flex', 
      height: '100vh', 
      fontFamily: 'Inter, system-ui, sans-serif',
      backgroundColor: '#f9fafb'
    }}>
      {/* Users Sidebar */}
      <div style={{ 
        width: '300px', 
        backgroundColor: 'white', 
        borderRight: '1px solid #e5e7eb',
        padding: '20px'
      }}>
        <h2 style={{ margin: '0 0 20px 0', fontSize: '20px', fontWeight: '600' }}>
          Team Chat
        </h2>
        <div>
          <h3 style={{ fontSize: '14px', fontWeight: '500', color: '#6b7280', marginBottom: '10px' }}>
            MEMBERS ({users.length})
          </h3>
          {users.map(user => (
            <div key={user.id} style={{ 
              display: 'flex', 
              alignItems: 'center', 
              padding: '10px',
              borderRadius: '8px',
              cursor: 'pointer',
              backgroundColor: currentUser?.id === user.id ? '#eff6ff' : 'transparent',
              border: currentUser?.id === user.id ? '1px solid #dbeafe' : '1px solid transparent',
              marginBottom: '5px'
            }}
            onClick={() => setCurrentUser(user)}
            >
              <div style={{ 
                width: '36px', 
                height: '36px', 
                borderRadius: '50%', 
                backgroundColor: '#e5e7eb',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '14px',
                fontWeight: '600',
                color: '#374151',
                marginRight: '12px',
                position: 'relative'
              }}>
                {user.name.charAt(0)}
                <div style={{
                  position: 'absolute',
                  bottom: '0',
                  right: '0',
                  width: '12px',
                  height: '12px',
                  borderRadius: '50%',
                  backgroundColor: getStatusColor(user.status),
                  border: '2px solid white'
                }}></div>
              </div>
              <div>
                <div style={{ fontWeight: '500', fontSize: '14px' }}>{user.name}</div>
                <div style={{ fontSize: '12px', color: '#6b7280', textTransform: 'capitalize' }}>
                  {user.status}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Chat Area */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
        {/* Messages */}
        <div style={{ 
          flex: 1, 
          padding: '20px', 
          overflowY: 'auto',
          backgroundColor: 'white'
        }}>
          {error && (
            <div style={{ 
              backgroundColor: '#fef2f2', 
              border: '1px solid #fecaca',
              color: '#dc2626',
              padding: '12px',
              borderRadius: '8px',
              marginBottom: '20px'
            }}>
              {error}
            </div>
          )}
          
          {messages.map(message => {
            const user = getUserById(message.userId);
            const isCurrentUser = message.userId === currentUser?.id;
            
            return (
              <div key={message.id} style={{ 
                display: 'flex', 
                marginBottom: '20px',
                justifyContent: isCurrentUser ? 'flex-end' : 'flex-start'
              }}>
                {!isCurrentUser && (
                  <div style={{ 
                    width: '32px', 
                    height: '32px', 
                    borderRadius: '50%', 
                    backgroundColor: '#e5e7eb',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: '12px',
                    fontWeight: '600',
                    color: '#374151',
                    marginRight: '12px',
                    flexShrink: 0
                  }}>
                    {user?.name.charAt(0)}
                  </div>
                )}
                
                <div style={{ maxWidth: '70%' }}>
                  {!isCurrentUser && (
                    <div style={{ 
                      fontSize: '12px', 
                      fontWeight: '500', 
                      color: '#374151',
                      marginBottom: '4px'
                    }}>
                      {user?.name}
                    </div>
                  )}
                  
                  <div style={{ 
                    backgroundColor: isCurrentUser ? '#3b82f6' : '#f3f4f6',
                    color: isCurrentUser ? 'white' : '#374151',
                    padding: '12px 16px',
                    borderRadius: '18px',
                    fontSize: '14px',
                    lineHeight: '1.4'
                  }}>
                    {message.text}
                  </div>
                  
                  <div style={{ 
                    fontSize: '11px', 
                    color: '#9ca3af',
                    marginTop: '4px',
                    textAlign: isCurrentUser ? 'right' : 'left'
                  }}>
                    {formatTimestamp(message.timestamp)}
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Message Input */}
        <div style={{ 
          padding: '20px', 
          borderTop: '1px solid #e5e7eb',
          backgroundColor: 'white'
        }}>
          <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-end' }}>
            <textarea
              value={currentMessage}
              onChange={(e) => setCurrentMessage(e.target.value)}
              onKeyPress={handleKeyPress}
              placeholder="Type a message..."
              style={{
                flex: 1,
                border: '1px solid #d1d5db',
                borderRadius: '12px',
                padding: '12px 16px',
                fontSize: '14px',
                resize: 'none',
                fontFamily: 'inherit',
                minHeight: '44px',
                maxHeight: '120px'
              }}
              rows={1}
            />
            <button
              onClick={sendMessage}
              disabled={!currentMessage.trim()}
              style={{
                backgroundColor: currentMessage.trim() ? '#3b82f6' : '#d1d5db',
                color: 'white',
                border: 'none',
                borderRadius: '12px',
                padding: '12px 20px',
                cursor: currentMessage.trim() ? 'pointer' : 'not-allowed',
                fontSize: '14px',
                fontWeight: '500',
                transition: 'background-color 0.2s'
              }}
            >
              Send
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ChatApp;`;

// Vue Counter Component - From actual fixture file
export const vueCounterComponent = `<template>
  <div class="counter-container">
    <h1>Vue Counter App</h1>
    <div class="counter-display">
      <p class="count">{{ count }}</p>
    </div>
    <div class="controls">
      <button @click="decrement" :disabled="count <= 0">-</button>
      <button @click="reset">Reset</button>
      <button @click="increment">+</button>
    </div>
    <div class="history">
      <h3>History</h3>
      <ul>
        <li v-for="(entry, index) in history" :key="index">
          {{ entry }}
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Counter',
  data() {
    return {
      count: 0,
      history: []
    };
  },
  methods: {
    increment() {
      this.count++;
      this.addToHistory(\`Incremented to \${this.count}\`);
    },
    decrement() {
      if (this.count > 0) {
        this.count--;
        this.addToHistory(\`Decremented to \${this.count}\`);
      }
    },
    reset() {
      this.count = 0;
      this.addToHistory('Reset to 0');
    },
    addToHistory(action) {
      this.history.unshift(action);
      if (this.history.length > 5) {
        this.history.pop();
      }
    }
  }
};
</script>

<style scoped>
.counter-container {
  max-width: 400px;
  margin: 0 auto;
  padding: 20px;
  text-align: center;
  font-family: Arial, sans-serif;
}

.counter-display {
  margin: 20px 0;
}

.count {
  font-size: 48px;
  font-weight: bold;
  color: #42b983;
}

.controls {
  display: flex;
  justify-content: center;
  gap: 10px;
  margin: 20px 0;
}

button {
  padding: 10px 20px;
  font-size: 18px;
  cursor: pointer;
  background-color: #42b983;
  color: white;
  border: none;
  border-radius: 4px;
  transition: background-color 0.3s;
}

button:hover:not(:disabled) {
  background-color: #35a372;
}

button:disabled {
  background-color: #ccc;
  cursor: not-allowed;
}

.history {
  margin-top: 30px;
}

.history ul {
  list-style: none;
  padding: 0;
}

.history li {
  padding: 5px;
  margin: 5px 0;
  background-color: #f0f0f0;
  border-radius: 4px;
}
</style>`;

// Svelte Form Component - From actual fixture file
export const svelteFormComponent = `<script>
  let name = '';
  let email = '';
  let message = '';
  let submitted = false;
  let errors = {};

  function validateForm() {
    errors = {};
    
    if (!name.trim()) {
      errors.name = 'Name is required';
    }
    
    if (!email.trim()) {
      errors.email = 'Email is required';
    } else if (!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email)) {
      errors.email = 'Invalid email format';
    }
    
    if (!message.trim()) {
      errors.message = 'Message is required';
    } else if (message.length < 10) {
      errors.message = 'Message must be at least 10 characters';
    }
    
    return Object.keys(errors).length === 0;
  }

  function handleSubmit() {
    if (validateForm()) {
      submitted = true;
      setTimeout(() => {
        name = '';
        email = '';
        message = '';
        submitted = false;
      }, 3000);
    }
  }

  function handleReset() {
    name = '';
    email = '';
    message = '';
    errors = {};
    submitted = false;
  }
</script>

<div class="form-container">
  <h1>Contact Form</h1>
  
  {#if submitted}
    <div class="success-message">
      Thank you for your submission! We'll get back to you soon.
    </div>
  {:else}
    <form on:submit|preventDefault={handleSubmit}>
      <div class="form-group">
        <label for="name">Name:</label>
        <input
          type="text"
          id="name"
          bind:value={name}
          class:error={errors.name}
          placeholder="Enter your name"
        />
        {#if errors.name}
          <span class="error-message">{errors.name}</span>
        {/if}
      </div>

      <div class="form-group">
        <label for="email">Email:</label>
        <input
          type="email"
          id="email"
          bind:value={email}
          class:error={errors.email}
          placeholder="Enter your email"
        />
        {#if errors.email}
          <span class="error-message">{errors.email}</span>
        {/if}
      </div>

      <div class="form-group">
        <label for="message">Message:</label>
        <textarea
          id="message"
          bind:value={message}
          class:error={errors.message}
          placeholder="Enter your message (min 10 characters)"
          rows="5"
        />
        {#if errors.message}
          <span class="error-message">{errors.message}</span>
        {/if}
      </div>

      <div class="form-actions">
        <button type="submit">Submit</button>
        <button type="button" on:click={handleReset}>Reset</button>
      </div>
    </form>
  {/if}

  <div class="form-preview">
    <h3>Preview:</h3>
    <p><strong>Name:</strong> {name || 'Not entered'}</p>
    <p><strong>Email:</strong> {email || 'Not entered'}</p>
    <p><strong>Message:</strong> {message || 'Not entered'}</p>
  </div>
</div>

<style>
  .form-container {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    font-family: Arial, sans-serif;
  }

  h1 {
    color: #ff3e00;
    text-align: center;
  }

  .form-group {
    margin-bottom: 20px;
  }

  label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
    color: #333;
  }

  input, textarea {
    width: 100%;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 4px;
    font-size: 16px;
    transition: border-color 0.3s;
  }

  input:focus, textarea:focus {
    outline: none;
    border-color: #ff3e00;
  }

  input.error, textarea.error {
    border-color: #f44336;
  }

  .error-message {
    color: #f44336;
    font-size: 14px;
    margin-top: 5px;
    display: block;
  }

  .form-actions {
    display: flex;
    gap: 10px;
    justify-content: center;
  }

  button {
    padding: 10px 20px;
    font-size: 16px;
    cursor: pointer;
    border: none;
    border-radius: 4px;
    transition: background-color 0.3s;
  }

  button[type="submit"] {
    background-color: #ff3e00;
    color: white;
  }

  button[type="submit"]:hover {
    background-color: #e03500;
  }

  button[type="button"] {
    background-color: #888;
    color: white;
  }

  button[type="button"]:hover {
    background-color: #666;
  }

  .success-message {
    padding: 15px;
    background-color: #4caf50;
    color: white;
    border-radius: 4px;
    text-align: center;
    margin: 20px 0;
  }

  .form-preview {
    margin-top: 30px;
    padding: 15px;
    background-color: #f5f5f5;
    border-radius: 4px;
  }

  .form-preview h3 {
    margin-top: 0;
    color: #666;
  }

  .form-preview p {
    margin: 10px 0;
    color: #333;
  }
</style>`;

// Export mapping for easy access by filename
export const FIXTURE_MAP = {
  'react-todo.jsx': reactTodoComponent,
  'react-counter.tsx': reactTypescriptComponent,
  'vue-weather.vue': vueCompositionComponent,
  'vue-counter.vue': vueCounterComponent,  // Added missing fixture
  'svelte-tasks.svelte': svelteComponent,
  'svelte-form.svelte': svelteFormComponent,  // Added missing fixture
  'html-calculator.html': htmlVanillaComponent,
  'react-chat.jsx': complexReactComponent,
} as const;

// Helper function to get fixture by filename
export function getFixture(filename: string): string {
  return FIXTURE_MAP[filename as keyof typeof FIXTURE_MAP] || '';
}

// List all available fixtures
export const AVAILABLE_FIXTURES = Object.keys(FIXTURE_MAP);